# Generated by Django 4.2.11 on 2025-03-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BNBUSD_1H',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=15)),
                ('high', models.DecimalField(decimal_places=2, max_digits=15)),
                ('low', models.DecimalField(decimal_places=2, max_digits=15)),
                ('close', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='BTCUSD_1H',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=15)),
                ('high', models.DecimalField(decimal_places=2, max_digits=15)),
                ('low', models.DecimalField(decimal_places=2, max_digits=15)),
                ('close', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ETHUSD_1H',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=15)),
                ('high', models.DecimalField(decimal_places=2, max_digits=15)),
                ('low', models.DecimalField(decimal_places=2, max_digits=15)),
                ('close', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='SOLUSD_1H',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=15)),
                ('high', models.DecimalField(decimal_places=2, max_digits=15)),
                ('low', models.DecimalField(decimal_places=2, max_digits=15)),
                ('close', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='SUIUSD_1H',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=15)),
                ('high', models.DecimalField(decimal_places=4, max_digits=15)),
                ('low', models.DecimalField(decimal_places=4, max_digits=15)),
                ('close', models.DecimalField(decimal_places=4, max_digits=15)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='XRPUSD_1H',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=15)),
                ('high', models.DecimalField(decimal_places=4, max_digits=15)),
                ('low', models.DecimalField(decimal_places=4, max_digits=15)),
                ('close', models.DecimalField(decimal_places=4, max_digits=15)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
