# Generated by Django 4.2.11 on 2025-04-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_bnbusd_4h_btcusd_4h_ethusd_4h_solusd_4h_suiusd_4h_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BNBUSD_E',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=15)),
                ('high', models.DecimalField(decimal_places=2, max_digits=15)),
                ('low', models.DecimalField(decimal_places=2, max_digits=15)),
                ('close', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='BTCUSD_E',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=15)),
                ('high', models.DecimalField(decimal_places=2, max_digits=15)),
                ('low', models.DecimalField(decimal_places=2, max_digits=15)),
                ('close', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ETHUSD_E',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=15)),
                ('high', models.DecimalField(decimal_places=2, max_digits=15)),
                ('low', models.DecimalField(decimal_places=2, max_digits=15)),
                ('close', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='SOLUSD_E',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=15)),
                ('high', models.DecimalField(decimal_places=2, max_digits=15)),
                ('low', models.DecimalField(decimal_places=2, max_digits=15)),
                ('close', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='SUIUSD_E',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=15)),
                ('high', models.DecimalField(decimal_places=4, max_digits=15)),
                ('low', models.DecimalField(decimal_places=4, max_digits=15)),
                ('close', models.DecimalField(decimal_places=4, max_digits=15)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='XRPUSD_E',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=15)),
                ('high', models.DecimalField(decimal_places=4, max_digits=15)),
                ('low', models.DecimalField(decimal_places=4, max_digits=15)),
                ('close', models.DecimalField(decimal_places=4, max_digits=15)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
